<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <IsAotCompatible>true</IsAotCompatible>
        <StripSymbols>false</StripSymbols>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>2025.3.3</Version>
        <Title>Gml.Pingo</Title>
        <Description>A simple library to ping Minecraft: Java/Bedrock edition servers that supports almost all versions.</Description>
        <Copyright>Recloud LLC</Copyright>
        <PackageProjectUrl>https://github.com/GamerVII-NET/Pingo</PackageProjectUrl>
        <RepositoryUrl>https://github.com/GamerVII-NET/Pingo</RepositoryUrl>
        <PackageTags>Minecraft, Ping</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>